### ISSUE TITLE
Keyboard shortcuts are not working

### ISSUE THREAD

**Issue by ranjeet692** [bpmn-io/bpmn-js-example-angular#11]
I was trying this repository and noticed no keyboard inputs are working except text input. Other options like delete, search, undo, redo keyboard shortcuts are not working as it works in https://demo.bpmn.io/

**Comment by pinussilvestrus** [comment]
Hi @ranjeet692 !

The keyboard shortcuts are simply not enabled in the created `BpmnModeler` (cf. [source](https://github.com/bpmn-io/bpmn-js-example-angular/blob/master/bpmn-js-app/src/app/diagram/diagram.component.ts#L54)). To enable you to have to add the `keyboard` config to the Modeler:

```js
this.bpmnJS = new BpmnJS({
   keyboard: { bindTo: document }
});
```

Do you think it's a good idea to have this per default in the angular example? If yes, we could consider opening a Pull request with the changes (or just you if you want to). We're open for contributions 👍🏻

**Comment by ranjeet692** [comment]
Hi @pinussilvestrus 

thanks for the solution. It will be good if you can add this as default or put any related link of bpmn.js documentation in README file.

**Comment by nikku** [comment]
Can we revert https://github.com/bpmn-io/bpmn-js-example-angular/commit/c7347ff27fb84f024b5ebf37f844cd88aeb1fa86 and link the relevant documentation instead? The default example bootstraps the viewer and for that one keyboard binding does not make any sense.

**Comment by pinussilvestrus** [comment]
Sure, good catch, I'll do it soon...
