### ISSUE TITLE
Data path ".builders['app-shell']" should have required property 'class'.

### ISSUE THREAD

**Issue by campa** [bpmn-io/bpmn-js-example-angular#15]
```
.. /git/temp/bpmn-js-example-angular/bpmn-js-app$ ng serve
Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
Error: Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
    at MergeMapSubscriber._registry.compile.pipe.operators_1.concatMap.validatorResult [as project] (/media/stefano/Windows8_OS/Tinvention/git/temp/bpmn-js-example-angular/bpmn-js-app/node_modules/@angular-devkit/core/src/workspace/workspace.js:215:42)
```
```
../git/temp/bpmn-js-example-angular/bpmn-js-app$ node -version
node: bad option: -version
.../git/temp/bpmn-js-example-angular/bpmn-js-app$ node -v
v10.14.2
```
Any suggestion ?

**Comment by nikku** [comment]
What are the exact steps that allow us to reproduce your issue?

**Comment by ahaeslich** [comment]
I could reproduce this issue with the following steps:

1. Clone the Repo
2. npm install
3. npm run build

The error shows during `npm run build`. While running `npm run all` the error is thrown while running `ng lint`.

node: 12.4.0
npm: 6.10.2

**Comment by nikku** [comment]
Seems like an angular cli / build system incompatibility, cf. [this StackOverflow hit](https://stackoverflow.com/questions/56393158/errors-data-path-buildersapp-shell-should-have-required-property-class). Looking into it.
