### ISSUE TITLE
A more complete example of integrating with an Angular app

### ISSUE THREAD

**Issue by ajlouie** [bpmn-io/bpmn-js-example-angular#18]
I wanted to find a more complete example of bpmn-js properties panels working with an Angular app, similar to [bpmn-io/bpmn-js-example-react-properties-panel](https://github.com/bpmn-io/bpmn-js-example-react-properties-panel), so I went ahead and made one (see PR #17 ).

Using this repo as a basis, I found a variety of other examples out there, especially [@central-factory/ngx-bpmn-modeler](https://github.com/central-factory/mono/tree/master/libs/ngx-bpmn-modeler), that pointed me in the right direction.

Along the way, I did some refactoring to better conform to Angular best practices. I can't claim that I did it right, but it's a step in the right direction.

**Comment by nikku** [comment]
First of all, thanks for your contribution!

To better understand the contribution I have a few questions:

* What is the difference between #17 (your PR) and [`ngx-bpmn-modeler`](https://github.com/central-factory/mono/tree/master/libs/ngx-bpmn-modeler)? 

* What kind of refactorings did you apply to accomplish the following:

    > Along the way, I did some refactoring to better conform to Angular best practices. I can't claim that I did it right, but it's a step in the right direction.

**Comment by ajlouie** [comment]
`ngx-bpmn-modeler` is structured as a module called from a directive, where all the providers, properties, etc. are injected via attributes. While it's a superior example of modular architecture / dependency injection, it's a bit over-architected for someone who is looking for a more straightforward/minimal example of integrating `bpmn-js` into Angular. `ngx-bpmn-modeler` also had no unit tests.

Most of the refactoring I did was to bring the example closer to the guidelines in the [Angular Style Guide](https://angular.io/guide/styleguide), and to bring the code up to 100% test coverage:
- Moved `HttpClient` into a service, rather than having DiagramComponent be responsible for both rendering the diagram AND asynchronously getting XML from a URL. This also did away with the need for the [`rx.ts`](https://github.com/bpmn-io/bpmn-js-example-angular/blob/master/bpmn-js-app/src/app/diagram/rx.ts), which was basically acting like a service anyway. ([Style 08-01](https://angular.io/guide/styleguide#talk-to-the-server-through-a-service))
- Moved HTML/CSS templates and styles into separate HTML and SCSS files ([Style 01-01](https://angular.io/guide/styleguide#style-01-01), [Style 05-04](https://angular.io/guide/styleguide#style-05-04))
- Broke apart bigger methods into smaller functions, so each could be unit-tested separately. ([Style 01-02](https://angular.io/guide/styleguide#style-01-02))
- Added some interfaces (in [./bpmn-js-app/src/app/_interfaces](https://github.com/sartography/bpmn-js-example-angular/tree/feature/properties-panel/bpmn-js-app/src/app/_interfaces)) to help with type hinting, linting, and debugging.
- Added unit tests for everything.

**Comment by nikku** [comment]
Sorry for leaving this issue and https://github.com/bpmn-io/bpmn-js-example-angular/pull/17 hanging!

We finally managed to discuss this internally and came to the conclusion that what you've proposed via https://github.com/bpmn-io/bpmn-js-example-angular/pull/17 is beyond the scope of this example.

We accept incremental improvements (parts of your PR). However, we don't accept changes that introduce additional boilerplate, scaffolding and so on. Reason: This blows up the example and makes it much harder for people to understand the essentials ("how to integrate bpmn-js into Angular powered applications").

In case you would like to host your more complete example somewhere and aim to keep it up to date with changing angular best practices: Please share the link to the repository with us and we are happy to include it in the README.


#### What this particular example is supposed to do:

* Show how to (easily) integrate bpmn-js into angular powered applications
* Show which _basic_ angular mechanisms are required to achieve this (retrieving a node, ...)

In this sense you could even argue that fetching the way people fetch with angular (HttpService and stuff) is beyond this simple example. People that use Angular surely know how to fetch things (and learning how to fetch the angular way is not the goal of this example).


#### What this example is __not__ supposed to do: 

* Bootstrap a complete angular applications, all strings attached (material UI, ...)
* Teach people how to write clean angular applications in general
