### ISSUE TITLE
Migrate from callbacks to Promises

### ISSUE THREAD

**Issue by ParkerM** [bpmn-io/bpmn-js-example-angular#32]
__Is your feature request related to a problem? Please describe__  

The example app logs a deprecation warning about using the callback version of `importXML`, and refers to the migration guide here: https://github.com/bpmn-io/bpmn-js-callbacks-to-promises

  
__Describe the solution you'd like__

The example app should use the Promise version of `importXML` in a way that conforms to Angular/RxJS conventions.  

__Additional context__

See my take on an implementation here: https://github.com/ParkerM/bpmn-js-example-angular/commit/3af59817f5d9  
I tried replicating the existing behavior, and everything seems to work the same from what I can tell.

I'd be happy to submit a PR, but figured I should open an issue beforehand to invite discussions around the most "correct" way to integrate the new API with Angular/RxJS that respects convention and also accounts for any caveats I may have missed.  
I imagine this is a common use case, so it'd be nice to have a solid vetted recipe for reference.

**Comment by nikku** [comment]
Your changes (https://github.com/ParkerM/bpmn-js-example-angular/commit/3af59817f5d9) look great, if you remove the debug logging.

Happy to take a contribution that improves this example :pray:.
