### ISSUE TITLE
Version upgrade (angular + bpmn-js +bpmn-js-properties-panel)

### ISSUE THREAD

**Issue by soori-reddy** [bpmn-io/bpmn-js-example-angular#36]
__Is your feature request related to a problem? Please describe__

finding challenges to get this working latest  Angular _ with custom properties

   "@angular/animations": "~13.2.4",
    "@angular/cdk": "^13.2.4",
    "@angular/common": "~13.2.4",
    "@angular/compiler": "~13.2.4",
 
      "bpmn-js": "^9.0.2",
      "bpmn-js-properties-panel": "^1.0.0-alpha.4",
       "@bpmn-io/properties-panel": "^0.11.0",

__Describe the solution you'd like__

 please  update this example to an advanced level

__Describe alternatives you've considered__

__Additional context__

**Comment by soori-reddy** [comment]
if possible please help with both light and dark theme support (material)

**Comment by nikku** [comment]
Please provide a comprehensive example what you need (and what is not covered already) as part of the issue description (or inside a CodeSandbox). We cannot help you otherwise.

**Comment by soori-reddy** [comment]
I try to set up on stack blitz , but not successful , Hope this helps

https://stackblitz.com/edit/angular-ivy-tm86pv


![2022-03-02_23-17-21](https://user-images.githubusercontent.com/83331029/156419701-46bb8642-8204-424d-879c-6f7e8feaaf97.png)

**Comment by soori-reddy** [comment]
![image](https://user-images.githubusercontent.com/83331029/156429245-62137899-cac4-4773-9062-5478d7ca222d.png)
it would be helpful if we can have an  example / update this repo  to have custom attributes in angular way instead of react /JSX

**Comment by pinussilvestrus** [comment]
> it would be helpful if we can have an example / update this repo to have custom attributes in angular way instead of react /JSX

It's currently not possible to provide custom properties in a non-preact way: https://github.com/bpmn-io/properties-panel/issues/6. In the meanwhile, you will have to configure your angular project to make your custom properties consumable. I think the best approach would be to keep your properties panel extension in [an own module](https://github.com/bpmn-io/bpmn-js-examples/tree/master/properties-panel-extension) and bundle it beforehand.

**Comment by soori-reddy** [comment]
hmm , can we expect tsx support in future  ?
trying to combine both world  (to make use of this library) fingers crossed

![image](https://user-images.githubusercontent.com/83331029/156525388-ad904d28-6856-4464-9d41-50ee339c4f58.png)

**Comment by soori-reddy** [comment]
i don't think this is right library for angular at this moment
![image](https://user-images.githubusercontent.com/83331029/156780469-bcc8b224-d5fb-4649-9c11-872d429fcc34.png)
