### ISSUE TITLE
Error with Angular 13

### ISSUE THREAD

**Issue by mehrad-rafigh** [bpmn-io/bpmn-js-example-angular#37]
__Describe the Bug__

Following the example here and using Angular 13 produces an error
```
Error: libs/ui/configurator/src/lib/components/viewer/viewer.component.ts:10:25 - error TS7016: Could not find a declaration file for module 'bpmn-js/dist/bpmn-modeler.production.min.js'. '/home/mehrad/dev/work/alfred/node_modules/bpmn-js/dist/bpmn-modeler.production.min.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/bpmn-js` if it exists or add a new declaration (.d.ts) file containing `declare module 'bpmn-js/dist/bpmn-modeler.production.min.js';`

10 import * as BpmnJS from "bpmn-js/dist/bpmn-modeler.production.min.js";
```

__Steps to Reproduce__

1. create new angular app with ng new test-bpmn-js
2. follow this example
3. ng serve 

__Expected Behavior__
Serving the application should not result in an error

__Environment__

- Host (Browser/Node version) Node 16 LTS
- OS: Debian
- Library version: 9.0.2

**Comment by barmac** [comment]
If I understand this correctly, the issue should be fixed when you add an appropriate declaration, according to https://stackoverflow.com/questions/41292559/could-not-find-a-declaration-file-for-module-module-name-path-to-module-nam

We are happy to accept external contributions. Please feel free to update the example and try out the suggested solution.

**Comment by barmac** [comment]
The repo is upgraded to Angular 15 now. Feel free to reopen the issue if the problem persists.
