### ISSUE TITLE
Showcase Modeler

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js-example-angular#8]
Hi thanks for all!! @nikku 

Is this project just for viewer or has the modeler as well? i'm trying to make it work here.. it renders.. but doesnt let me add elements (i drop in view and shows a icon of forbidden).. any ideas?

_Originally posted by @mariohmol in https://github.com/bpmn-io/bpmn-js-example-angular/issues/6#issuecomment-456860616_

**Comment by nikku** [comment]
@mariohmol cf. https://github.com/bpmn-io/bpmn-js-example-angular/blob/master/bpmn-js-app/src/app/diagram/diagram.component.ts#L24. The modeler is supported, too.

**Comment by nikku** [comment]
I updated the README accordingly: https://github.com/bpmn-io/bpmn-js-example-angular/commit/5184f71377fef5336510adf787350f9685a5d70e.

**Comment by mariohmol** [comment]
check it out https://github.com/mariohmol/ng-bpmn
